# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

from PyInstaller.utils.hooks import collect_all

# Collect all pydantic_settings modules and data
pydantic_settings_datas, pydantic_settings_binaries, pydantic_settings_hiddenimports = collect_all('pydantic_settings')

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=[(r'C:\Users\wanzh\anaconda3\Library\bin\ffi.dll', '.'), (r'C:\Users\wanzh\anaconda3\Library\bin\sqlite3.dll', '.')] + pydantic_settings_binaries,
    datas=[('C:\\Users\\wanzh\\Documents\\kimi\\workspace\\dist', 'dist')] + pydantic_settings_datas,
    hiddenimports=[
        'app.main',
        'app.config',
        'app.database',
        'app.models',
        'app.schemas',
        'app.routers.auth',
        'app.routers.session',
        'app.routers.graph',
        'app.routers.baseline',
        'app.services.nlp',
        'app.services.health',
        'sqlalchemy.dialects.sqlite',
        'bcrypt',
        'jose',
        'jose.jwt',
        'jose.backends',
        'passlib.handlers.bcrypt',
        'pydantic_settings',
        'pydantic_settings.sources',
        'dotenv',
        'email_validator',
        'python_multipart',
        'starlette',
        'starlette.requests',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'anyio',
        'anyio._backends._asyncio',
        'sniffio',
        'h11',
        'typing_extensions',
        'idna',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'PySide6', 'PySide2', 'PyQt5', 'PyQt6',
        'numpy', 'pandas', 'scipy', 'sklearn',
        'IPython', 'jedi', 'parso', 'notebook', 'jupyter',
        'black', 'yapf', 'lxml', 'PIL', 'Pillow',
        'tkinter', '_tkinter', 'Tcl', 'tk',
        'plotly', 'bokeh', 'sympy', 'statsmodels', 'seaborn',
        'django', 'flask', 'tornado', 'twisted', 'scrapy',
        'pyarrow', 'zmq', 'pynacl', 'OpenSSL',
        'boto3', 'botocore', 'azure', 'google',
        'tables', 'h5py', 'netCDF4', 'xarray', 'dask',
        'astropy', 'biopython', 'Bio',
        'mypy', 'pytest', 'coverage', 'sphinx', 'nose',
        'cython', 'Cython', 'numba', 'llvmlite',
        'torch', 'torchvision', 'tensorflow', 'keras',
        'transformers', 'spacy', 'gensim', 'nltk',
        'opencv', 'cv2', 'imageio', 'moviepy',
        'pyaudio', 'speech_recognition', 'pydub',
        'requests_cache', 'redis', 'pymongo',
        'psycopg2', 'MySQLdb', 'pymysql',
        'sqlalchemy.ext.asyncio', 'alembic',
        'httpx', 'httpx', 'sanic', 'quart', 'falcon',
        'grpc', 'grpcio', 'protobuf',
        'pydantic.v1', 'pydantic_settings',
        'orjson', 'ujson', 'msgpack', 'cbor2',
        'marshmallow', 'attrs', 'cattrs',
        'rich', 'textual', 'tqdm', 'progress',
        'tabulate', 'prettytable', 'terminaltables',
        'click_completion', 'click_repl', 'fire',
        'invoke', 'fabric', 'paramiko',
        'pexpect', 'ansible', 'salt',
        'docker', 'kubernetes', 'helm',
        'vault', 'consul', 'etcd', 'zookeeper',
        'kafka', 'rabbitmq', 'pika', 'amqp', 'celery',
        'redis', 'memcache', 'mongoengine', 'odmantic',
        'tortoise', 'tortoise_orm', 'peewee', 'pony',
        'wtforms', 'django_extensions', 'django_rest_framework',
        'graphene', 'fastapi_users', 'fastapi_mail',
        'uvloop', 'httptools', 'websockets', 'wsproto',
        'python_socketio', 'aiofiles', 'aiosqlite',
        'prisma', 'sqlmodel', 'piccolo',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
