# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

from PyInstaller.utils.hooks import collect_all, collect_data_files

# 收集 pydantic_settings 的全部子模块和数据
pydantic_settings_datas, pydantic_settings_binaries, pydantic_settings_hiddenimports = collect_all('pydantic_settings')

# 收集 jieba 词典数据文件（dict.txt 等）
jieba_datas = collect_data_files('jieba')

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=pydantic_settings_binaries,
    datas=[
        ('../dist', 'dist'),            # 前端静态文件
        ('alembic', 'alembic'),          # 数据库迁移脚本
        ('alembic.ini', '.'),            # alembic 配置文件
    ] + jieba_datas + pydantic_settings_datas,
    hiddenimports=[
        # 应用自身模块
        'app.main',
        'app.config',
        'app.database',
        'app.models',
        'app.schemas',
        'app.redis_client',
        'app.rate_limit',
        'app.middleware.permission',
        # 路由
        'app.routers.auth',
        'app.routers.session',
        'app.routers.graph',
        'app.routers.baseline',
        'app.routers.stt',
        'app.routers.state_sync',
        'app.routers.backup',
        'app.routers.scale',
        'app.routers.lexicon',
        'app.routers.decline',
        'app.routers.notification',
        'app.routers.voice_message',
        'app.routers.family_sync',
        'app.routers.share',
        'app.routers.training',
        'app.routers.llm',
        'app.routers.websocket',
        'app.routers.sync',
        # 服务
        'app.services.nlp',
        'app.services.health',
        'app.services.crypto',
        'app.services.key_manager',
        'app.services.kms',
        'app.services.audit',
        'app.services.events',
        'app.services.e2ee',
        'app.services.baseline_personal',
        'app.services.connection_manager',
        'app.services.decline',
        'app.services.emotion_analyzer',
        'app.services.llm_client',
        'app.services.metrics',
        'app.services.notification_service',
        'app.services.scales',
        'app.services.sync_protocol',
        'app.services.temporal_parser',
        # 第三方库
        'jwt',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.postgresql',
        'bcrypt',
        'passlib.handlers.bcrypt',
        'pydantic_settings',
        'pydantic_settings.sources',
        'dotenv',
        'python_multipart',
        'starlette',
        'starlette.requests',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'anyio',
        'anyio._backends._asyncio',
        'sniffio',
        'h11',
        'typing_extensions',
        'idna',
        'certifi',
        'redis',
        'alembic',
        'prometheus_client',
    ] + pydantic_settings_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'PySide6', 'PySide2', 'PyQt5', 'PyQt6',
        'numpy', 'pandas', 'scipy', 'sklearn',
        'IPython', 'jedi', 'parso', 'notebook', 'jupyter',
        'black', 'yapf', 'lxml', 'PIL', 'Pillow',
        'tkinter', '_tkinter', 'Tcl', 'tk',
        'plotly', 'bokeh', 'sympy', 'statsmodels', 'seaborn',
        'django', 'flask', 'tornado', 'twisted', 'scrapy',
        'tables', 'h5py', 'netCDF4', 'xarray', 'dask',
        'astropy', 'biopython', 'Bio',
        'mypy', 'pytest', 'coverage', 'sphinx', 'nose',
        'cython', 'Cython', 'numba', 'llvmlite',
        'torch', 'torchvision', 'tensorflow', 'keras',
        'transformers', 'spacy', 'gensim', 'nltk',
        'opencv', 'cv2', 'imageio', 'moviepy',
        'pyaudio', 'speech_recognition', 'pydub',
        'pymongo',
        'MySQLdb', 'pymysql',
        'sanic', 'quart', 'falcon',
        'grpc', 'grpcio', 'protobuf',
        'orjson', 'ujson', 'msgpack', 'cbor2',
        'marshmallow', 'attrs', 'cattrs',
        'rich', 'textual', 'tqdm', 'progress',
        'tabulate', 'prettytable', 'terminaltables',
        'click_completion', 'click_repl', 'fire',
        'invoke', 'fabric', 'paramiko',
        'pexpect', 'ansible', 'salt',
        'docker', 'kubernetes', 'helm',
        'vault', 'consul', 'etcd', 'zookeeper',
        'kafka', 'rabbitmq', 'pika', 'amqp', 'celery',
        'memcache', 'mongoengine', 'odmantic',
        'tortoise', 'tortoise_orm', 'peewee', 'pony',
        'wtforms', 'django_extensions', 'django_rest_framework',
        'graphene', 'fastapi_users', 'fastapi_mail',
        'httptools', 'websockets', 'wsproto',
        'python_socketio', 'aiofiles', 'aiosqlite',
        'prisma', 'sqlmodel', 'piccolo',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='weave',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
